[tool.poetry]
name = "docs"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
mkdocs = "^1.6.1"
mkdocs-material = "^9.5.49"
mkdocs-autorefs = "^1.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
